### ISSUE TITLE
Size of em

### ISSUE THREAD

**Issue by arandamerinoalberto** [TheRandomCrew/TicTacToe-JS#13]
https://github.com/Israel-Laguan/TicTacToe-JS/blob/9e364a84be1f8036185a08785785756461e73c20/src/css/main.css#L28

Why you have used the format em instead of px? 

PD: Esto será una buena manera de practicar inglés en las issues. Estoy comenzando por mirarme el css e iré avanzando hasta llegar a Javascript. Línea a línea. Gracias Israel.

**Comment by Israel-Laguan** [comment]
# Short answer 

So the style can be more responsive. Using `px` is good on design but for support mobile, TVs and all the sizes in the middle, relative units are better.

# Long answer 

When you use `em` you are setting up against the base pixels informed in the browser. CSS compares the pixel unit given from the browser, and that is important because this can be different than "normal" pixels from 'px' units. By using `em` you ensure the pixel is relative to the user's browser.

**Comment by Israel-Laguan** [comment]
As a side note, is even better to use `rem` units, but you have to create a good design system behind!
